#!/bin/bash

set -eu

cd "$(dirname "${BASH_SOURCE:-$0}")"

{
  echo '# 
# flake8: noqa
"""[Auto Generated by ../../../update_installing_dependencies_notebook.sh] Prepare script for install dependencies."""

requirements = """'

  poetry export --without-hashes | sed -e 's/\\/\\\\/g'
  # NOTE(hori-ryota): hashもつけたいがDatabricksにて以下のエラーが生じるので妥協している
  # ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
  #     colorama from https://files.pythonhosted.org/packages/44/98/5b86278fbbf250d239ae0ecb724f8572af1c91f4a11edf4d36a206189440/colorama-0.4.4-py2.py3-none-any.whl#sha256=9f47eda37229f68eee03b24b9748937c7dc3868f906e8ba69fbcbdd3bc5dc3e2 (from sacrebleu==2.0.0->-r requirements.txt (line 828))

  echo '"""

f = open("requirements.txt", "w")
f.write(requirements)
f.close()

# COMMAND ----------

# MAGIC %pip install -r requirements.txt

# COMMAND ----------

# MAGIC %sh rm requirements.txt'
} > './AutoML-develop/common/01_install_dependencies/01_install_external_dependencies.py'
